apiVersion: apps/v1
kind: Deployment
metadata:
  name: delio-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delio-app
  template:
    metadata:
      labels:
        app: delio-app
    spec:
      containers:
        - name: app
          image: kaneofthrones/km-node-app:latest
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: delio-app
spec:
  selector:
    app: delio-app
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
